version: '3'
services:
  app:
    container_name: tech_descomplica_app
    build: .
    command: npm run dev
    ports:
      - 3333:3000
    volumes:
      - .:/usr/app
    depends_on:
      - mysql_db
    restart: always
  mysql_db:
    container_name: mysql_db
    image: mysql:5.7
    hostname: mysql_db
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: descomplica
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
    # networks:
      # - wpsite
  # phpmyadmin
#   phpmyadmin:
#     depends_on:
#       - db
#     image: phpmyadmin/phpmyadmin
#     restart: always
#     ports:
#       - '8080:80'
#     environment:
#       PMA_HOST: db
#       MYSQL_ROOT_PASSWORD: secret
#     # networks:
#       # - wpsite
# # networks:
# #   wpsite:
volumes:
  db_data: