version: '3'
services:
  app:
    container_name: tech_descomplica_app
    build: .
    command: npm run dev
    ports:
      - 3333:3000
    volumes:
      - .:/usr/app
    depends_on:
      - mysql_db
    restart: always
  mysql_db:
    container_name: mysql_db
    image: mysql:5.7
    hostname: mysql_db
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: descomplica
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret

volumes:
  db_data: